#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DACNHM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Rangbuoc")]
	public partial class dbQLHMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDiaDiemHienMau(DiaDiemHienMau instance);
    partial void UpdateDiaDiemHienMau(DiaDiemHienMau instance);
    partial void DeleteDiaDiemHienMau(DiaDiemHienMau instance);
    partial void InsertNguoiHienMau(NguoiHienMau instance);
    partial void UpdateNguoiHienMau(NguoiHienMau instance);
    partial void DeleteNguoiHienMau(NguoiHienMau instance);
    partial void InsertNhomMau(NhomMau instance);
    partial void UpdateNhomMau(NhomMau instance);
    partial void DeleteNhomMau(NhomMau instance);
    partial void InsertPhieuTinhTrangSucKhoe(PhieuTinhTrangSucKhoe instance);
    partial void UpdatePhieuTinhTrangSucKhoe(PhieuTinhTrangSucKhoe instance);
    partial void DeletePhieuTinhTrangSucKhoe(PhieuTinhTrangSucKhoe instance);
    partial void InsertPhieuXacNhanHienMau(PhieuXacNhanHienMau instance);
    partial void UpdatePhieuXacNhanHienMau(PhieuXacNhanHienMau instance);
    partial void DeletePhieuXacNhanHienMau(PhieuXacNhanHienMau instance);
    partial void InsertQuanLyHienMau(QuanLyHienMau instance);
    partial void UpdateQuanLyHienMau(QuanLyHienMau instance);
    partial void DeleteQuanLyHienMau(QuanLyHienMau instance);
    partial void InsertSanPham(SanPham instance);
    partial void UpdateSanPham(SanPham instance);
    partial void DeleteSanPham(SanPham instance);
    partial void InsertTinhTrangSucKhoe(TinhTrangSucKhoe instance);
    partial void UpdateTinhTrangSucKhoe(TinhTrangSucKhoe instance);
    partial void DeleteTinhTrangSucKhoe(TinhTrangSucKhoe instance);
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    #endregion
		
		public dbQLHMDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RangbuocConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLHMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLHMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLHMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLHMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietThuong> ChiTietThuongs
		{
			get
			{
				return this.GetTable<ChiTietThuong>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiemHienMau> DiaDiemHienMaus
		{
			get
			{
				return this.GetTable<DiaDiemHienMau>();
			}
		}
		
		public System.Data.Linq.Table<DotHienMau> DotHienMaus
		{
			get
			{
				return this.GetTable<DotHienMau>();
			}
		}
		
		public System.Data.Linq.Table<NguoiHienMau> NguoiHienMaus
		{
			get
			{
				return this.GetTable<NguoiHienMau>();
			}
		}
		
		public System.Data.Linq.Table<NhomMau> NhomMaus
		{
			get
			{
				return this.GetTable<NhomMau>();
			}
		}
		
		public System.Data.Linq.Table<PhieuTinhTrangSucKhoe> PhieuTinhTrangSucKhoes
		{
			get
			{
				return this.GetTable<PhieuTinhTrangSucKhoe>();
			}
		}
		
		public System.Data.Linq.Table<PhieuXacNhanHienMau> PhieuXacNhanHienMaus
		{
			get
			{
				return this.GetTable<PhieuXacNhanHienMau>();
			}
		}
		
		public System.Data.Linq.Table<QuanLyHienMau> QuanLyHienMaus
		{
			get
			{
				return this.GetTable<QuanLyHienMau>();
			}
		}
		
		public System.Data.Linq.Table<SanPham> SanPhams
		{
			get
			{
				return this.GetTable<SanPham>();
			}
		}
		
		public System.Data.Linq.Table<TinhTrangSucKhoe> TinhTrangSucKhoes
		{
			get
			{
				return this.GetTable<TinhTrangSucKhoe>();
			}
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietThuong")]
	public partial class ChiTietThuong
	{
		
		private string _MaSP;
		
		private string _SoLuong;
		
		private string _MaPhieuXacNhan;
		
		public ChiTietThuong()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSP", DbType="VarChar(10)")]
		public string MaSP
		{
			get
			{
				return this._MaSP;
			}
			set
			{
				if ((this._MaSP != value))
				{
					this._MaSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="NVarChar(50)")]
		public string SoLuong
		{
			get
			{
				return this._SoLuong;
			}
			set
			{
				if ((this._SoLuong != value))
				{
					this._SoLuong = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuXacNhan", DbType="VarChar(10)")]
		public string MaPhieuXacNhan
		{
			get
			{
				return this._MaPhieuXacNhan;
			}
			set
			{
				if ((this._MaPhieuXacNhan != value))
				{
					this._MaPhieuXacNhan = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiemHienMau")]
	public partial class DiaDiemHienMau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDiaDiem;
		
		private string _Diachi;
		
		private string _TenDiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDiaDiemChanging(string value);
    partial void OnMaDiaDiemChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnTenDiaDiemChanging(string value);
    partial void OnTenDiaDiemChanged();
    #endregion
		
		public DiaDiemHienMau()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDiaDiem", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDiaDiem
		{
			get
			{
				return this._TenDiaDiem;
			}
			set
			{
				if ((this._TenDiaDiem != value))
				{
					this.OnTenDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._TenDiaDiem = value;
					this.SendPropertyChanged("TenDiaDiem");
					this.OnTenDiaDiemChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DotHienMau")]
	public partial class DotHienMau
	{
		
		private string _MaDiaDiem;
		
		private string _MaPhieuXacNhan;
		
		private System.Nullable<System.DateTime> _ThoiGianToChuc;
		
		public DotHienMau()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="VarChar(50)")]
		public string MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this._MaDiaDiem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuXacNhan", DbType="VarChar(10)")]
		public string MaPhieuXacNhan
		{
			get
			{
				return this._MaPhieuXacNhan;
			}
			set
			{
				if ((this._MaPhieuXacNhan != value))
				{
					this._MaPhieuXacNhan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianToChuc", DbType="Date")]
		public System.Nullable<System.DateTime> ThoiGianToChuc
		{
			get
			{
				return this._ThoiGianToChuc;
			}
			set
			{
				if ((this._ThoiGianToChuc != value))
				{
					this._ThoiGianToChuc = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiHienMau")]
	public partial class NguoiHienMau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNgHien;
		
		private string _TenNgHien;
		
		private string _MaNhomMau;
		
		private string _Sdt;
		
		private string _SoCCCD;
		
		private System.Nullable<int> _LanHien;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _DiaChi;
		
		private EntitySet<PhieuTinhTrangSucKhoe> _PhieuTinhTrangSucKhoes;
		
		private EntitySet<PhieuXacNhanHienMau> _PhieuXacNhanHienMaus;
		
		private EntityRef<NhomMau> _NhomMau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNgHienChanging(int value);
    partial void OnMaNgHienChanged();
    partial void OnTenNgHienChanging(string value);
    partial void OnTenNgHienChanged();
    partial void OnMaNhomMauChanging(string value);
    partial void OnMaNhomMauChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnSoCCCDChanging(string value);
    partial void OnSoCCCDChanged();
    partial void OnLanHienChanging(System.Nullable<int> value);
    partial void OnLanHienChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public NguoiHienMau()
		{
			this._PhieuTinhTrangSucKhoes = new EntitySet<PhieuTinhTrangSucKhoe>(new Action<PhieuTinhTrangSucKhoe>(this.attach_PhieuTinhTrangSucKhoes), new Action<PhieuTinhTrangSucKhoe>(this.detach_PhieuTinhTrangSucKhoes));
			this._PhieuXacNhanHienMaus = new EntitySet<PhieuXacNhanHienMau>(new Action<PhieuXacNhanHienMau>(this.attach_PhieuXacNhanHienMaus), new Action<PhieuXacNhanHienMau>(this.detach_PhieuXacNhanHienMaus));
			this._NhomMau = default(EntityRef<NhomMau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgHien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaNgHien
		{
			get
			{
				return this._MaNgHien;
			}
			set
			{
				if ((this._MaNgHien != value))
				{
					this.OnMaNgHienChanging(value);
					this.SendPropertyChanging();
					this._MaNgHien = value;
					this.SendPropertyChanged("MaNgHien");
					this.OnMaNgHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNgHien", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNgHien
		{
			get
			{
				return this._TenNgHien;
			}
			set
			{
				if ((this._TenNgHien != value))
				{
					this.OnTenNgHienChanging(value);
					this.SendPropertyChanging();
					this._TenNgHien = value;
					this.SendPropertyChanged("TenNgHien");
					this.OnTenNgHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomMau", DbType="VarChar(10)")]
		public string MaNhomMau
		{
			get
			{
				return this._MaNhomMau;
			}
			set
			{
				if ((this._MaNhomMau != value))
				{
					if (this._NhomMau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNhomMauChanging(value);
					this.SendPropertyChanging();
					this._MaNhomMau = value;
					this.SendPropertyChanged("MaNhomMau");
					this.OnMaNhomMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCCCD", DbType="Char(20) NOT NULL", CanBeNull=false)]
		public string SoCCCD
		{
			get
			{
				return this._SoCCCD;
			}
			set
			{
				if ((this._SoCCCD != value))
				{
					this.OnSoCCCDChanging(value);
					this.SendPropertyChanging();
					this._SoCCCD = value;
					this.SendPropertyChanged("SoCCCD");
					this.OnSoCCCDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LanHien", DbType="Int")]
		public System.Nullable<int> LanHien
		{
			get
			{
				return this._LanHien;
			}
			set
			{
				if ((this._LanHien != value))
				{
					this.OnLanHienChanging(value);
					this.SendPropertyChanging();
					this._LanHien = value;
					this.SendPropertyChanged("LanHien");
					this.OnLanHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="NVarChar(250)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(250)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(50)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiHienMau_PhieuTinhTrangSucKhoe", Storage="_PhieuTinhTrangSucKhoes", ThisKey="MaNgHien", OtherKey="MaNgHien")]
		public EntitySet<PhieuTinhTrangSucKhoe> PhieuTinhTrangSucKhoes
		{
			get
			{
				return this._PhieuTinhTrangSucKhoes;
			}
			set
			{
				this._PhieuTinhTrangSucKhoes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiHienMau_PhieuXacNhanHienMau", Storage="_PhieuXacNhanHienMaus", ThisKey="MaNgHien", OtherKey="MaNgHien")]
		public EntitySet<PhieuXacNhanHienMau> PhieuXacNhanHienMaus
		{
			get
			{
				return this._PhieuXacNhanHienMaus;
			}
			set
			{
				this._PhieuXacNhanHienMaus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomMau_NguoiHienMau", Storage="_NhomMau", ThisKey="MaNhomMau", OtherKey="MaNhomMau", IsForeignKey=true)]
		public NhomMau NhomMau
		{
			get
			{
				return this._NhomMau.Entity;
			}
			set
			{
				NhomMau previousValue = this._NhomMau.Entity;
				if (((previousValue != value) 
							|| (this._NhomMau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomMau.Entity = null;
						previousValue.NguoiHienMaus.Remove(this);
					}
					this._NhomMau.Entity = value;
					if ((value != null))
					{
						value.NguoiHienMaus.Add(this);
						this._MaNhomMau = value.MaNhomMau;
					}
					else
					{
						this._MaNhomMau = default(string);
					}
					this.SendPropertyChanged("NhomMau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuTinhTrangSucKhoes(PhieuTinhTrangSucKhoe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiHienMau = this;
		}
		
		private void detach_PhieuTinhTrangSucKhoes(PhieuTinhTrangSucKhoe entity)
		{
			this.SendPropertyChanging();
			entity.NguoiHienMau = null;
		}
		
		private void attach_PhieuXacNhanHienMaus(PhieuXacNhanHienMau entity)
		{
			this.SendPropertyChanging();
			entity.NguoiHienMau = this;
		}
		
		private void detach_PhieuXacNhanHienMaus(PhieuXacNhanHienMau entity)
		{
			this.SendPropertyChanging();
			entity.NguoiHienMau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomMau")]
	public partial class NhomMau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNhomMau;
		
		private string _TenNhomMau;
		
		private EntitySet<NguoiHienMau> _NguoiHienMaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNhomMauChanging(string value);
    partial void OnMaNhomMauChanged();
    partial void OnTenNhomMauChanging(string value);
    partial void OnTenNhomMauChanged();
    #endregion
		
		public NhomMau()
		{
			this._NguoiHienMaus = new EntitySet<NguoiHienMau>(new Action<NguoiHienMau>(this.attach_NguoiHienMaus), new Action<NguoiHienMau>(this.detach_NguoiHienMaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNhomMau", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNhomMau
		{
			get
			{
				return this._MaNhomMau;
			}
			set
			{
				if ((this._MaNhomMau != value))
				{
					this.OnMaNhomMauChanging(value);
					this.SendPropertyChanging();
					this._MaNhomMau = value;
					this.SendPropertyChanged("MaNhomMau");
					this.OnMaNhomMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNhomMau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenNhomMau
		{
			get
			{
				return this._TenNhomMau;
			}
			set
			{
				if ((this._TenNhomMau != value))
				{
					this.OnTenNhomMauChanging(value);
					this.SendPropertyChanging();
					this._TenNhomMau = value;
					this.SendPropertyChanged("TenNhomMau");
					this.OnTenNhomMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomMau_NguoiHienMau", Storage="_NguoiHienMaus", ThisKey="MaNhomMau", OtherKey="MaNhomMau")]
		public EntitySet<NguoiHienMau> NguoiHienMaus
		{
			get
			{
				return this._NguoiHienMaus;
			}
			set
			{
				this._NguoiHienMaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NguoiHienMaus(NguoiHienMau entity)
		{
			this.SendPropertyChanging();
			entity.NhomMau = this;
		}
		
		private void detach_NguoiHienMaus(NguoiHienMau entity)
		{
			this.SendPropertyChanging();
			entity.NhomMau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuTinhTrangSucKhoe")]
	public partial class PhieuTinhTrangSucKhoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuTTSK;
		
		private System.DateTime _NgayKham;
		
		private System.Nullable<int> _MaNgHien;
		
		private string _MaTTSK;
		
		private EntityRef<NguoiHienMau> _NguoiHienMau;
		
		private EntityRef<TinhTrangSucKhoe> _TinhTrangSucKhoe;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuTTSKChanging(string value);
    partial void OnMaPhieuTTSKChanged();
    partial void OnNgayKhamChanging(System.DateTime value);
    partial void OnNgayKhamChanged();
    partial void OnMaNgHienChanging(System.Nullable<int> value);
    partial void OnMaNgHienChanged();
    partial void OnMaTTSKChanging(string value);
    partial void OnMaTTSKChanged();
    #endregion
		
		public PhieuTinhTrangSucKhoe()
		{
			this._NguoiHienMau = default(EntityRef<NguoiHienMau>);
			this._TinhTrangSucKhoe = default(EntityRef<TinhTrangSucKhoe>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuTTSK", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuTTSK
		{
			get
			{
				return this._MaPhieuTTSK;
			}
			set
			{
				if ((this._MaPhieuTTSK != value))
				{
					this.OnMaPhieuTTSKChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuTTSK = value;
					this.SendPropertyChanged("MaPhieuTTSK");
					this.OnMaPhieuTTSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKham", DbType="DateTime NOT NULL")]
		public System.DateTime NgayKham
		{
			get
			{
				return this._NgayKham;
			}
			set
			{
				if ((this._NgayKham != value))
				{
					this.OnNgayKhamChanging(value);
					this.SendPropertyChanging();
					this._NgayKham = value;
					this.SendPropertyChanged("NgayKham");
					this.OnNgayKhamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgHien", DbType="Int")]
		public System.Nullable<int> MaNgHien
		{
			get
			{
				return this._MaNgHien;
			}
			set
			{
				if ((this._MaNgHien != value))
				{
					if (this._NguoiHienMau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNgHienChanging(value);
					this.SendPropertyChanging();
					this._MaNgHien = value;
					this.SendPropertyChanged("MaNgHien");
					this.OnMaNgHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTTSK", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaTTSK
		{
			get
			{
				return this._MaTTSK;
			}
			set
			{
				if ((this._MaTTSK != value))
				{
					if (this._TinhTrangSucKhoe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTTSKChanging(value);
					this.SendPropertyChanging();
					this._MaTTSK = value;
					this.SendPropertyChanged("MaTTSK");
					this.OnMaTTSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiHienMau_PhieuTinhTrangSucKhoe", Storage="_NguoiHienMau", ThisKey="MaNgHien", OtherKey="MaNgHien", IsForeignKey=true)]
		public NguoiHienMau NguoiHienMau
		{
			get
			{
				return this._NguoiHienMau.Entity;
			}
			set
			{
				NguoiHienMau previousValue = this._NguoiHienMau.Entity;
				if (((previousValue != value) 
							|| (this._NguoiHienMau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiHienMau.Entity = null;
						previousValue.PhieuTinhTrangSucKhoes.Remove(this);
					}
					this._NguoiHienMau.Entity = value;
					if ((value != null))
					{
						value.PhieuTinhTrangSucKhoes.Add(this);
						this._MaNgHien = value.MaNgHien;
					}
					else
					{
						this._MaNgHien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiHienMau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhTrangSucKhoe_PhieuTinhTrangSucKhoe", Storage="_TinhTrangSucKhoe", ThisKey="MaTTSK", OtherKey="MaTTSK", IsForeignKey=true)]
		public TinhTrangSucKhoe TinhTrangSucKhoe
		{
			get
			{
				return this._TinhTrangSucKhoe.Entity;
			}
			set
			{
				TinhTrangSucKhoe previousValue = this._TinhTrangSucKhoe.Entity;
				if (((previousValue != value) 
							|| (this._TinhTrangSucKhoe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TinhTrangSucKhoe.Entity = null;
						previousValue.PhieuTinhTrangSucKhoes.Remove(this);
					}
					this._TinhTrangSucKhoe.Entity = value;
					if ((value != null))
					{
						value.PhieuTinhTrangSucKhoes.Add(this);
						this._MaTTSK = value.MaTTSK;
					}
					else
					{
						this._MaTTSK = default(string);
					}
					this.SendPropertyChanged("TinhTrangSucKhoe");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuXacNhanHienMau")]
	public partial class PhieuXacNhanHienMau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaPhieuXacNhan;
		
		private System.DateTime _NgayHienMau;
		
		private string _SoLuongMauHien;
		
		private string _MaDiaDiem;
		
		private System.Nullable<int> _MaNgHien;
		
		private string _MaDonViQL;
		
		private EntityRef<NguoiHienMau> _NguoiHienMau;
		
		private EntityRef<QuanLyHienMau> _QuanLyHienMau;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhieuXacNhanChanging(string value);
    partial void OnMaPhieuXacNhanChanged();
    partial void OnNgayHienMauChanging(System.DateTime value);
    partial void OnNgayHienMauChanged();
    partial void OnSoLuongMauHienChanging(string value);
    partial void OnSoLuongMauHienChanged();
    partial void OnMaDiaDiemChanging(string value);
    partial void OnMaDiaDiemChanged();
    partial void OnMaNgHienChanging(System.Nullable<int> value);
    partial void OnMaNgHienChanged();
    partial void OnMaDonViQLChanging(string value);
    partial void OnMaDonViQLChanged();
    #endregion
		
		public PhieuXacNhanHienMau()
		{
			this._NguoiHienMau = default(EntityRef<NguoiHienMau>);
			this._QuanLyHienMau = default(EntityRef<QuanLyHienMau>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhieuXacNhan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaPhieuXacNhan
		{
			get
			{
				return this._MaPhieuXacNhan;
			}
			set
			{
				if ((this._MaPhieuXacNhan != value))
				{
					this.OnMaPhieuXacNhanChanging(value);
					this.SendPropertyChanging();
					this._MaPhieuXacNhan = value;
					this.SendPropertyChanged("MaPhieuXacNhan");
					this.OnMaPhieuXacNhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHienMau", DbType="DateTime NOT NULL")]
		public System.DateTime NgayHienMau
		{
			get
			{
				return this._NgayHienMau;
			}
			set
			{
				if ((this._NgayHienMau != value))
				{
					this.OnNgayHienMauChanging(value);
					this.SendPropertyChanging();
					this._NgayHienMau = value;
					this.SendPropertyChanged("NgayHienMau");
					this.OnNgayHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuongMauHien", DbType="VarChar(50)")]
		public string SoLuongMauHien
		{
			get
			{
				return this._SoLuongMauHien;
			}
			set
			{
				if ((this._SoLuongMauHien != value))
				{
					this.OnSoLuongMauHienChanging(value);
					this.SendPropertyChanging();
					this._SoLuongMauHien = value;
					this.SendPropertyChanged("SoLuongMauHien");
					this.OnSoLuongMauHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDiaDiem", DbType="VarChar(50)")]
		public string MaDiaDiem
		{
			get
			{
				return this._MaDiaDiem;
			}
			set
			{
				if ((this._MaDiaDiem != value))
				{
					this.OnMaDiaDiemChanging(value);
					this.SendPropertyChanging();
					this._MaDiaDiem = value;
					this.SendPropertyChanged("MaDiaDiem");
					this.OnMaDiaDiemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNgHien", DbType="Int")]
		public System.Nullable<int> MaNgHien
		{
			get
			{
				return this._MaNgHien;
			}
			set
			{
				if ((this._MaNgHien != value))
				{
					if (this._NguoiHienMau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNgHienChanging(value);
					this.SendPropertyChanging();
					this._MaNgHien = value;
					this.SendPropertyChanged("MaNgHien");
					this.OnMaNgHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonViQL", DbType="VarChar(10)")]
		public string MaDonViQL
		{
			get
			{
				return this._MaDonViQL;
			}
			set
			{
				if ((this._MaDonViQL != value))
				{
					if (this._QuanLyHienMau.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDonViQLChanging(value);
					this.SendPropertyChanging();
					this._MaDonViQL = value;
					this.SendPropertyChanged("MaDonViQL");
					this.OnMaDonViQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiHienMau_PhieuXacNhanHienMau", Storage="_NguoiHienMau", ThisKey="MaNgHien", OtherKey="MaNgHien", IsForeignKey=true)]
		public NguoiHienMau NguoiHienMau
		{
			get
			{
				return this._NguoiHienMau.Entity;
			}
			set
			{
				NguoiHienMau previousValue = this._NguoiHienMau.Entity;
				if (((previousValue != value) 
							|| (this._NguoiHienMau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiHienMau.Entity = null;
						previousValue.PhieuXacNhanHienMaus.Remove(this);
					}
					this._NguoiHienMau.Entity = value;
					if ((value != null))
					{
						value.PhieuXacNhanHienMaus.Add(this);
						this._MaNgHien = value.MaNgHien;
					}
					else
					{
						this._MaNgHien = default(Nullable<int>);
					}
					this.SendPropertyChanged("NguoiHienMau");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLyHienMau_PhieuXacNhanHienMau", Storage="_QuanLyHienMau", ThisKey="MaDonViQL", OtherKey="MaDonViQL", IsForeignKey=true)]
		public QuanLyHienMau QuanLyHienMau
		{
			get
			{
				return this._QuanLyHienMau.Entity;
			}
			set
			{
				QuanLyHienMau previousValue = this._QuanLyHienMau.Entity;
				if (((previousValue != value) 
							|| (this._QuanLyHienMau.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._QuanLyHienMau.Entity = null;
						previousValue.PhieuXacNhanHienMaus.Remove(this);
					}
					this._QuanLyHienMau.Entity = value;
					if ((value != null))
					{
						value.PhieuXacNhanHienMaus.Add(this);
						this._MaDonViQL = value.MaDonViQL;
					}
					else
					{
						this._MaDonViQL = default(string);
					}
					this.SendPropertyChanged("QuanLyHienMau");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanLyHienMau")]
	public partial class QuanLyHienMau : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDonViQL;
		
		private string _TenDonViQL;
		
		private string _Diachi;
		
		private string _Sdt;
		
		private string _Email;
		
		private EntitySet<PhieuXacNhanHienMau> _PhieuXacNhanHienMaus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDonViQLChanging(string value);
    partial void OnMaDonViQLChanged();
    partial void OnTenDonViQLChanging(string value);
    partial void OnTenDonViQLChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public QuanLyHienMau()
		{
			this._PhieuXacNhanHienMaus = new EntitySet<PhieuXacNhanHienMau>(new Action<PhieuXacNhanHienMau>(this.attach_PhieuXacNhanHienMaus), new Action<PhieuXacNhanHienMau>(this.detach_PhieuXacNhanHienMaus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDonViQL", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDonViQL
		{
			get
			{
				return this._MaDonViQL;
			}
			set
			{
				if ((this._MaDonViQL != value))
				{
					this.OnMaDonViQLChanging(value);
					this.SendPropertyChanging();
					this._MaDonViQL = value;
					this.SendPropertyChanged("MaDonViQL");
					this.OnMaDonViQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDonViQL", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TenDonViQL
		{
			get
			{
				return this._TenDonViQL;
			}
			set
			{
				if ((this._TenDonViQL != value))
				{
					this.OnTenDonViQLChanging(value);
					this.SendPropertyChanging();
					this._TenDonViQL = value;
					this.SendPropertyChanged("TenDonViQL");
					this.OnTenDonViQLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="QuanLyHienMau_PhieuXacNhanHienMau", Storage="_PhieuXacNhanHienMaus", ThisKey="MaDonViQL", OtherKey="MaDonViQL")]
		public EntitySet<PhieuXacNhanHienMau> PhieuXacNhanHienMaus
		{
			get
			{
				return this._PhieuXacNhanHienMaus;
			}
			set
			{
				this._PhieuXacNhanHienMaus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuXacNhanHienMaus(PhieuXacNhanHienMau entity)
		{
			this.SendPropertyChanging();
			entity.QuanLyHienMau = this;
		}
		
		private void detach_PhieuXacNhanHienMaus(PhieuXacNhanHienMau entity)
		{
			this.SendPropertyChanging();
			entity.QuanLyHienMau = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
	public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaSp;
		
		private string _LoaiSp;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaSpChanging(string value);
    partial void OnMaSpChanged();
    partial void OnLoaiSpChanging(string value);
    partial void OnLoaiSpChanged();
    #endregion
		
		public SanPham()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaSp", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaSp
		{
			get
			{
				return this._MaSp;
			}
			set
			{
				if ((this._MaSp != value))
				{
					this.OnMaSpChanging(value);
					this.SendPropertyChanging();
					this._MaSp = value;
					this.SendPropertyChanged("MaSp");
					this.OnMaSpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiSp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string LoaiSp
		{
			get
			{
				return this._LoaiSp;
			}
			set
			{
				if ((this._LoaiSp != value))
				{
					this.OnLoaiSpChanging(value);
					this.SendPropertyChanging();
					this._LoaiSp = value;
					this.SendPropertyChanged("LoaiSp");
					this.OnLoaiSpChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TinhTrangSucKhoe")]
	public partial class TinhTrangSucKhoe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTTSK;
		
		private string _LoaiTTSK;
		
		private EntitySet<PhieuTinhTrangSucKhoe> _PhieuTinhTrangSucKhoes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTTSKChanging(string value);
    partial void OnMaTTSKChanged();
    partial void OnLoaiTTSKChanging(string value);
    partial void OnLoaiTTSKChanged();
    #endregion
		
		public TinhTrangSucKhoe()
		{
			this._PhieuTinhTrangSucKhoes = new EntitySet<PhieuTinhTrangSucKhoe>(new Action<PhieuTinhTrangSucKhoe>(this.attach_PhieuTinhTrangSucKhoes), new Action<PhieuTinhTrangSucKhoe>(this.detach_PhieuTinhTrangSucKhoes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTTSK", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTTSK
		{
			get
			{
				return this._MaTTSK;
			}
			set
			{
				if ((this._MaTTSK != value))
				{
					this.OnMaTTSKChanging(value);
					this.SendPropertyChanging();
					this._MaTTSK = value;
					this.SendPropertyChanged("MaTTSK");
					this.OnMaTTSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTTSK", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string LoaiTTSK
		{
			get
			{
				return this._LoaiTTSK;
			}
			set
			{
				if ((this._LoaiTTSK != value))
				{
					this.OnLoaiTTSKChanging(value);
					this.SendPropertyChanging();
					this._LoaiTTSK = value;
					this.SendPropertyChanged("LoaiTTSK");
					this.OnLoaiTTSKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TinhTrangSucKhoe_PhieuTinhTrangSucKhoe", Storage="_PhieuTinhTrangSucKhoes", ThisKey="MaTTSK", OtherKey="MaTTSK")]
		public EntitySet<PhieuTinhTrangSucKhoe> PhieuTinhTrangSucKhoes
		{
			get
			{
				return this._PhieuTinhTrangSucKhoes;
			}
			set
			{
				this._PhieuTinhTrangSucKhoes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuTinhTrangSucKhoes(PhieuTinhTrangSucKhoe entity)
		{
			this.SendPropertyChanging();
			entity.TinhTrangSucKhoe = this;
		}
		
		private void detach_PhieuTinhTrangSucKhoes(PhieuTinhTrangSucKhoe entity)
		{
			this.SendPropertyChanging();
			entity.TinhTrangSucKhoe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PassAdmin;
		
		private string _Hoten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPassAdminChanging(string value);
    partial void OnPassAdminChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PassAdmin
		{
			get
			{
				return this._PassAdmin;
			}
			set
			{
				if ((this._PassAdmin != value))
				{
					this.OnPassAdminChanging(value);
					this.SendPropertyChanging();
					this._PassAdmin = value;
					this.SendPropertyChanged("PassAdmin");
					this.OnPassAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
